### PR TITLE
Added Powershell target with Invoke-WebRequest client.

### PR DESCRIPTION
**Pull request by bobmclaren**
Addresses enhancement issue #75 .

### CODE REVIEW

**Comment by paul-aquino** [comment]
Did this ever get officially merged into the main branch?

**Comment by kenmaglio** [comment]
Status?

**Comment by kenmaglio** [comment]
Can we get this re-built - It looks like the issues in Travis-CI was build issues on the core package - stuff with Node.

@bobmclaren can you request a rebuild on the PR yourself?

**Comment by bobmclaren** [comment]
Sorry @kenmaglio, I resubmitted but the checks still fail due to Node issues.  Lame.

**Comment by kenmaglio** [comment]
@bobmclaren I've tried emailing the company, to see if we can get any movement.

**Comment by thibaultcha** [comment]
@darrenjennings and @ahmadnassri are now official maintainers of httpsnippet, they can help move this forward :)

**Comment by kenmaglio** [comment]
@thibaultcha  Are we sure?  I've tried to reach out, and nothing.

**Comment by thibaultcha** [comment]
@kenmaglio Yep. Where did you reach out to them? Reminder that both have a daily job and are taking maintainership of this project as part a time duty :)

**Comment by darrenjennings** [comment]
@kenmaglio yes sorry to say we have not yet "fully taken off" in the http snippet maintenance rocket ship. We will begin triage and take good care of this package ASAP. As @thibaultcha says this is a part time duty that we only just recently committed to. We appreciate your patience and hope to make it better soon!

**Comment by kenmaglio** [comment]
@darrenjennings Thank you for responding. We have just been waiting ( not your fault ) on this PR for PostMan support of PowerShell. If there is anything I can help with, not that I'm 100% great with node. But whatever I can do to help let me know.

**Comment by kenmaglio** [comment]
@thibaultcha I guess I was figuring while this is open source, it's also part of Kong or owned by that company so it shouldn't be a side project - just on free time. Sorry I assumed  :/

**Pull request closed without merging**
