### PR TITLE
update javascript fetch request to match node-fetch

### PR DESCRIPTION
**Pull request by jonasholbech**
Vanilla JS did not return the json from the request, the node.js version does, now they should behave the same

### CODE REVIEW

**Review by erunion — CHANGES_REQUESTED** [review]
Can you update the tests for the JS target? They need this line added to them.

**Comment by jonasholbech** [comment]
Let me see if I can find those :-)

**Comment by erunion** [comment]
Here you go: https://github.com/Kong/httpsnippet/tree/master/test/fixtures/output/javascript/fetch

**Comment by jonasholbech** [comment]
thanks @erunion

**Review by reynolek — APPROVED** [review]

**Comment by reynolek** [comment]
Thanks for the contribution @jonasholbech!

**Pull request merged**
