### PR TITLE
Fix JSON body for fetch

### PR DESCRIPTION
**Pull request by jonahsnider**
The fetch API will convert the `body` parameter to a string before sending the request. For bodies that are JSON, the JSON object will get converted to a string and become `[object Object]`.

This uses `JSON.stringify()` to convert the object into a JSON string before sending the request.

### CODE REVIEW

**Comment by jonahsnider** [comment]
```shell
$ sudo apt-get install -qq --yes python3 php5-curl php5-cli
210E: Unable to locate package php5-curl
211E: Package 'php5-cli' has no installation candidate
```
https://github.com/Kong/httpsnippet/blob/c780dad09b014a1bb28e463b4b058b2d40ae2124/.travis.yml#L10
Looks like the same error is still present in the installation of `php5-cli`, which is why tests are failing.

**Comment by sebastianhaas** [comment]
@darrenjennings would you mind running this again if the CI problem is resolved by now?

**Comment by darrenjennings** [comment]
@sebastianhaas thanks for the note, this was due to #146, which is now fixed. Rerunning and will look shortly

**Comment by darrenjennings** [comment]
@pizzafox would you mind rebasing onto master so CI will run the tests?

**Comment by darrenjennings** [comment]
It looks like the test fixtures for `fetch` will need to be updated

**Comment by jonahsnider** [comment]
This broke a bunch of tests (that are flawed right now) that are looking for a JSON object rather than the string version to be the body.

**Comment by develohpanda** [comment]
Closing this PR in favor of https://github.com/Kong/httpsnippet/pull/179

**Pull request closed without merging**
