### PR TITLE
new target: Perl5

### PR DESCRIPTION
**Pull request by jgabriels**
added target for Perl

### CODE REVIEW

**Comment by darrenjennings** [comment]
@jgabriels thanks for the contribution. our test suite is stable on `master` if you would kindly rebase and add output fixtures and fix and linting issues. See #128 for inspiration.

**Comment by wbraswell** [comment]
@darrenjennings 
I'm following this issue because @jgabriels and I just discussed it.
Has anything changed since your last comment in 2019, or is the process still the same?

**Comment by erunion** [comment]
@wbraswell No, this PR needs to be recreated under the new directory structure and TypeScript codebase.

**Comment by filfreire** [comment]
Closing, uses old way of adding a target.

**Pull request closed without merging**
