### PR TITLE
Use `console.error` when logging errors in JavaScript fetch

### PR DESCRIPTION
**Pull request by jonahsnider**
The `console` object has a function for logging errors and should be used in the fetch target when an error is encountered.

### CODE REVIEW

**Comment by darrenjennings** [comment]
@pizzafox thanks for the contribution! Can you update the test outputs? see the travis failures for direction.

**Comment by jonahsnider** [comment]
The error is because `php5-cli` has no installation candidate. See #146.

**Comment by darrenjennings** [comment]
@pizzafox should be fixed now if you could rebase. thanks!

**Comment by jonahsnider** [comment]
Looks like this broke a bunch of tests expecting `console.log` to be present. https://travis-ci.org/Kong/httpsnippet/jobs/602972287#L1446-L1447

**Comment by darrenjennings** [comment]
@pizzafox the tests snapshot the output. Can you update the corresponding fixtures? 
https://github.com/Kong/httpsnippet/tree/master/test/fixtures/output/javascript/fetch

**Review by darrenjennings — APPROVED** [review]

**Pull request merged**
