### PR TITLE
fix: bug where FormData in the js fetch target wasn't applied

### PR DESCRIPTION
**Pull request by erunion**
* [x] Fixes a bug in the JS `fetch` target where `FormData` was being set to a `form` variable but never actually inserted. into the body of the fetch call.
* [x] Stops the JS fetch target from setting an empty object of `headers`.
* [x] Slightly cleans up the noise around the actual fetch call and indents the promise handling.

### CODE REVIEW

**Comment by jbwyme** [comment]
Hey just wanted to check in on the status of this! I believe this is causing incorrect code to be generated in our ReadMe docs.

**Comment by erunion** [comment]
@jbwyme You've already got this fix if you're a ReadMe customer because we run a fork (http://npm.im/@readme/httpsnippet) that have these changes. What's the bug you're seeing?

**Comment by jbwyme** [comment]
Ah gotcha, perhaps this is unrelated. Here's the loom I shared with support: https://www.loom.com/share/06da93107f4b40f88172d680507ac99d

**Comment by erunion** [comment]
@jbwyme Gotcha, that hit my desk yesterday.

**Comment by reynolek** [comment]
Fixed merge conflict injected from the PR that removed node 8

**Review by reynolek — APPROVED** [review]

**Pull request merged**
