### PR TITLE
Add Golang

### PR DESCRIPTION
**Pull request by montanaflynn**

### CODE REVIEW

**Comment by ahmadnassri** [comment]
great! are you going to add multipart support and tests? (see node:request for full example)

**Comment by montanaflynn** [comment]
I skipped the multipart for now since all the other targets except request didn't have them and the example JSON only showed the text property. Shouldn't be too difficult to implement, I'll look into it.

**Comment by thibaultcha** [comment]
Also update the README adding Go in the list of languages + documentation for options

**Comment by montanaflynn** [comment]
Done. The README is [missing options](https://github.com/ahmadnassri/httpsnippet#target-options) for all the other languages.

**Pull request merged**
